name: linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cxx: [g++-10]
        build_type: [Debug]
        std: [20]
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Update apt
        run: |
          sudo apt-get update

      - name: Install apt packages
        run: >
          sudo apt-get install -y libudev-dev libgl-dev libx11-xcb-dev libfontenc-dev libxaw7-dev 
          libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev 
          libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev 
          libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev libxcb-xkb-dev 
          libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev
          libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev
          libxcb-util-dev libpng-dev

      - name: Update apt 2
        run: |
          sudo apt-get update

      - name: Upgrade pip
        run: |
          pip3 install --upgrade pip

      - name: Install and configure Conan
        run: |
          pip3 install conan==1.62.0
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan profile update settings.build_type=Debug default
          conan profile show default

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: CMake Configure
        working-directory: ${{runner.workspace}}/build
        env:
          CXX: ${{matrix.cxx}}
#          CXXFLAGS: ${{matrix.cxxflags}}
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_MODULE_PATH=$PWD -DENABLE_TESTS=False \
                $GITHUB_WORKSPACE

      - name: CMake Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config ${{matrix.build_type}}

#      - name: Test
#        working-directory: ${{runner.workspace}}/build/
#        run: ctest -V -C ${{matrix.build_type}} --output-on-failure

      - name: cpack
        working-directory: ${{runner.workspace}}/build
        run: cpack
